services:
  conduit:
    build: .
    image: apibench/honojs
    tty: true
    networks: [realworld]

  newman:
    build: ../newman
    image: apibench/newman
    tty: true
    networks: [realworld]
    depends_on:
      conduit:
        condition: service_started

networks:
  realworld: {}
